AD_SECTIONS = {
    "Auto, Bike & Boat": [
        "auto_parts_tires",
        "boats_boat_accessories",
        "bicycles_accessories",
        "motorcycle_parts_accessories",
    ],
    "Tickets & Admission": [
        "train_public_transport",
        "comedy_cabaret",
        "vouchers",
        "kids",
        "concerts",
        "sports",
        "theater_musical",
        "other_tickets",
    ],
    "Electronics": [
        "audio_hifi",
        "photo",
        "mobile_phones_telephones",
        "household_appliances",
        "consoles",
        "laptops",
        "pcs",
        "pc_accessories_software",
        "tablets_ereaders",
        "tv_video",
        "video_games",
        "other_electronics",
    ],
    "Family, Children & Baby": [
        "elder_care",
        "baby_kids_clothing",
        "baby_kids_shoes",
        "baby_equipment",
        "baby_seats_child_seats",
        "babysitter_childcare",
        "strollers_buggy",
        "children_room_furniture",
        "toys",
        "other_family_children_baby",
    ],
    "Leisure, Hobby & Neighborhood": [
        "esoteric_spiritual",
        "food_drink",
        "leisure_activities",
        "crafts_handmade",
        "art_antiques",
        "artists_musicians",
        "model_building",
        "travel_event_services",
        "collectibles",
        "sports_camping",
        "flea_market",
        "lost_found",
        "other_leisure_hobby_neighborhood",
    ],
    "Home & Garden": [
        "bathroom",
        "office",
        "decoration",
        "home_garden_services",
        "garden_accessories_plants",
        "home_textiles",
        "diy",
        "kitchen_dining_room",
        "lighting",
        "bedroom",
        "living_room",
        "other_home_garden",
    ],
    "Pets": [
        "fish",
        "dogs",
        "cats",
        "small_animals",
        "farm_animals",
        "horses",
        "pet_care_training",
        "birds",
        "pet_accessories",
    ],
    "Fashion & Beauty": [
        "beauty_health",
        "womens_clothing",
        "womens_shoes",
        "mens_clothing",
        "mens_shoes",
        "bags_accessories",
        "watches_jewelry",
        "other_fashion_beauty",
    ],
    "Music, Movies & Books": [
        "books_magazines",
        "office_supplies",
        "comics",
        "textbooks_school_study",
        "films_dvds",
        "music_cds",
        "musical_instruments",
        "other_music_movies_books",
    ],
}
